["FILE ALLOCATION CONFIGURATION"]
BYTES_PER_VALUE = "2"
VALUES_PER_LINE = "4"
BUF_SAMPLES = "16384"
SHIFT_MULT = "5"

["SD CONFIGURATION"]
SD_CS_PIN = "10"
SPI_CLOCK_MHZ = "50"

["ADC CONFIGURATION"]
USE_AVG_MODE = "0"
NUM_RESULTS = "8192"
ADC_SAMPLEN = "4"
ADC_FACTOR_VAL = "4"

["GCLK CONFIGURATION"]
GCLK_DIV_FACTOR = "4"
ADC_GCLK = "2" # // use generic clock 2 instead of 1 so we can customize prescaler without affecting other peripherals

["ADC INPUT PINS"]
ADC0_INPUT_0 = "ADC_INPUTCTRL_MUXPOS_AIN0"
ADC0_INPUT_1 = "ADC_INPUTCTRL_MUXPOS_AIN5"
ADC1_INPUT_0 = "ADC_INPUTCTRL_MUXPOS_AIN0"
ADC1_INPUT_1 = "ADC_INPUTCTRL_MUXPOS_AIN1"

["DEBUG PRINT CONFIGURATION"]
DEBUG_R0_P0 = "0"
DEBUG_R0_P1 = "0"
DEBUG_R1_P0 = "0"
DEBUG_R1_P1 = "0"
